const fs = require("fs");
const path = require("path");

const SITE_URL = "https://farhanbalouch.com";
const OUTPUT = path.join(__dirname, "data", "knowledge.js");
const MAX_PAGES = Number(process.env.MAX_PAGES || 80);

function normalizeUrl(value) {
  try {
    const url = new URL(value, SITE_URL);
    if (url.origin !== new URL(SITE_URL).origin) return null;
    url.hash = "";
    url.search = "";
    if (url.pathname !== "/") url.pathname = url.pathname.replace(/\/+$/, "");
    return url.toString();
  } catch {
    return null;
  }
}

function htmlToText(html) {
  return html
    .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, " ")
    .replace(/<noscript[^>]*>[\s\S]*?<\/noscript>/gi, " ")
    .replace(/<!--[\s\S]*?-->/g, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/gi, "'")
    .replace(/\s+/g, " ")
    .trim();
}

function getMeta(html, name) {
  const pattern = new RegExp(`<meta[^>]+(?:name|property)=["']${name}["'][^>]+content=["']([^"']*)["'][^>]*>`, "i");
  return html.match(pattern)?.[1]?.trim() || "";
}

function getTitle(html) {
  return html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/\s+/g, " ").trim() || "";
}

function getLinks(html) {
  const links = [];
  const regex = /<a[^>]+href=["']([^"']+)["'][^>]*>/gi;
  let match;
  while ((match = regex.exec(html))) {
    const normalized = normalizeUrl(match[1]);
    if (normalized) links.push(normalized);
  }
  return [...new Set(links)];
}

function getJsonLd(html) {
  const result = [];
  const regex = /<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;
  let match;
  while ((match = regex.exec(html))) {
    try {
      result.push(JSON.parse(match[1].trim()));
    } catch {}
  }
  return result;
}

async function fetchHtml(url) {
  const response = await fetch(url, {
    headers: { "User-Agent": "Balouch-AI-Knowledge-Sync/1.0" },
    redirect: "follow"
  });
  if (!response.ok) throw new Error(`${response.status} ${response.statusText}`);
  return response.text();
}

async function getSitemapUrls() {
  const candidates = [
    `${SITE_URL}/sitemap.xml`,
    `${SITE_URL}/sitemap_index.xml`
  ];

  for (const sitemap of candidates) {
    try {
      const xml = await fetchHtml(sitemap);
      const urls = [...xml.matchAll(/<loc>\s*([^<]+?)\s*<\/loc>/gi)]
        .map(match => normalizeUrl(match[1]))
        .filter(Boolean);
      if (urls.length) return urls.slice(0, MAX_PAGES);
    } catch {}
  }
  return [];
}

async function main() {
  const discovered = new Set(await getSitemapUrls());
  discovered.add(SITE_URL);

  const queue = [...discovered];
  const pages = [];
  const seen = new Set();

  while (queue.length && pages.length < MAX_PAGES) {
    const url = queue.shift();
    if (!url || seen.has(url)) continue;
    seen.add(url);

    try {
      const html = await fetchHtml(url);
      const page = {
        url,
        title: getTitle(html),
        description: getMeta(html, "description") || getMeta(html, "og:description"),
        text: htmlToText(html).slice(0, 30000),
        jsonLd: getJsonLd(html)
      };

      pages.push(page);

      for (const link of getLinks(html)) {
        if (!seen.has(link) && !queue.includes(link) && queue.length < MAX_PAGES * 3) {
          queue.push(link);
        }
      }

      console.log(`Synced ${pages.length}/${MAX_PAGES}: ${url}`);
    } catch (error) {
      console.warn(`Skipped ${url}: ${error.message}`);
    }
  }

  if (!pages.length) {
    throw new Error("No pages could be fetched from farhanbalouch.com");
  }

  const knowledge = {
    source: SITE_URL,
    syncedAt: new Date().toISOString(),
    pageCount: pages.length,
    pages
  };

  const file = `// AUTO-GENERATED by sync.js — do not edit manually.\nconst websiteKnowledge = ${JSON.stringify(knowledge, null, 2)};\n\nif (typeof window !== "undefined") {\n  window.BALOUCH_KNOWLEDGE = websiteKnowledge;\n}\n\nif (typeof module !== "undefined" && module.exports) {\n  module.exports = { websiteKnowledge };\n}\n`;

  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, file, "utf8");
  console.log(`Knowledge sync complete: ${pages.length} pages -> ${OUTPUT}`);
}

main().catch(error => {
  console.error("Knowledge sync failed:", error);
  process.exit(1);
});
